### PR TITLE
jQuery no conflict for widget. (need for compatability with other libs)

### PR DESCRIPTION
**Pull request by pahaz**

### CODE REVIEW

**Comment by pahaz** [comment]
Oh, sory. changes only in three lines. Other changes is a line feed bug.

**Comment by ghost** [comment]
I like the idea of namespacing, however shouldn't the elfinder library itself be registered within that namespace?

**Comment by pahaz** [comment]
I don`t understand your question. 

If you tall about `window.elFinder` - them will be available in the global namespace, and will use it to correct the runtime libraries jQuery.

Or, if you tall about `$.elFinder widget` - them will be aviliable only in `jQuery_aLfinder.elFinder widget`.

**Comment by ghost** [comment]
That's not what I meant, but nevermind, you're correct anyway. I'll add this manually since I can't automatically merge anymore.

**Comment by ghost** [comment]
Ok, I added this to master and django1.5 branch. I slightly modified the namespace name for consistency with naming in yawd-admin. Is it ok now for you?

**Comment by pahaz** [comment]
Yes thanks. Close?

**Comment by ghost** [comment]
so everything is fine fine now, thanks for reporting!

**Pull request closed without merging**
