### PR TITLE
Default - settings unicode paths!

### PR DESCRIPTION
**Pull request by pahaz**

### CODE REVIEW

**Comment by ghost** [comment]
did the path (not being unicode) cause you any problems?

**Comment by pahaz** [comment]
Yes, i can`t upload file with my (russian) language names.

**Comment by ghost** [comment]
I think it should be better to  enforce unicode at the driver level. Maybe something like "self._root = self._normpath(u'%s' % self._options['path'])" in base.py, line 194 fixes it for you? (so that we don't need explicit unicode paths in the optionset configuration). Please check and let me know, I think it's important not to rely on the configuration for fixing an erroneous behavior, especially having the possibility of custom optionsets in mind.

**Comment by pahaz** [comment]
Of course you're right, I've wanted to do this, but could not determine the place, because not so well studied your code. 

My pool is only a quick fix. I think that this question is carefully you really need more research. Since the core Django can see the same problem, maybe it is not so easy to solve, or it has some pitfalls.

**Comment by ghost** [comment]
I have tracked down the issue with utf-8 filenames and the master is now updated with a fix. Please report back if the latest master is working for you to close the issue.

**Comment by boobby** [comment]
Great! Your patch works fine and I can upload folders of utf-8 filenames.
But i suspect there is still a bug. The utf-8 folders do not  work  fine in the root folders. It was perfect under a subdirectory.

**Comment by ghost** [comment]
Hello, I can't reproduce the problem to be honest! I would like to know the optionset you are you using (if it's custom please paste it here) and which operation fails. You cannot create utf-8 directories under the root? Does the path to the driver contain utf-8 charaters? It's working for me, but i'd like to reproduce this.

**Comment by boobby** [comment]
lol,I have come to know how to solve my problems now. 
In the settings of ELFINDER_CONNECTOR_OPTION_SETS:
'path' : join(settings.MEDIA_ROOT, u'files') should be  replace   'path' : join(settings.MEDIA_ROOT, 'files'),
force declare the path to unicode.

**Comment by ghost** [comment]
Ok thank you all, I'm merging this request as a good practice, and will enforce unicode paths in the code base as well.

**Pull request merged**
